### ISSUE TITLE
Streamlit or some other framework?

### ISSUE THREAD

**Issue by rakeshJn** [IBM/lakevision#14]
Let's discuss here what framework we should use going forward. While Streamlit is great to get things out quickly, it does have quite a few limitations, for example cookie handling, alternate navigation etc.

Just opening this issue for any feedback related to whether we should continue with Streamlit or move over to Flask or....?

**Comment by therealslimjp** [comment]
i am fine with streamlit for now, i like it because of its easy integration with dataframes, but i dont really know how well it scales. 

But i can work with flask too.

**Comment by rakeshJn** [comment]
I have discussed with some in-house experts. While Flask+React is the most popular framework, another alternate suggested is FastAPI+Svelte.
Just putting it out there..... I am checking what Svelte can help with.

**Comment by juancappi** [comment]
For the backend, I lean towards FastAPI. It's more modern than Flask, it has built-in type check and pydantic integration, built-in support for Oauth2. Both are solid options for backend development, but FastAPI offers more features out of the box.

React is definitely a more popular choice, but does come with a learning curve. I hear that svelte is simpler and a great option for non-UI developers.

**Comment by rakeshJn** [comment]
I am playing with fastapi and svelte and it seems to be quite nice. I will somewhat cleanup my code and put it in a separate branch for others to see/try.

**Comment by rakeshJn** [comment]
Add the still work in progress stuff in branch named `new_arch` in its own (temp) folder `new_arch` without touching existing stuff.

**Comment by rakeshJn** [comment]
Finally, merged everything to main branch, it is Svelte + Fastapi.
Closing this one.
