### ISSUE TITLE
Sample data is limited by batch size

### ISSUE THREAD

**Issue by rakeshJn** [IBM/lakevision#9]
When displaying sample data in the first tab, it is supposed to show n number of records, where n is sample size selected. However, in some cases, the records shown are less, even if the table/partition has more records.
The root cause is the fact that we are getting the arrow_batch_reader from table_scan and only using the first one, w/o checking the number of records it has. If it has less records than n, we show less records.

See: https://github.com/IBM/lakevision/blob/main/lake_viewer.py#L183

**Comment by deveshgoyal1000** [comment]
hello, Can you provide sample Catalog?

**Comment by rakeshJn** [comment]
hi, working on in under #10

**Comment by deveshgoyal1000** [comment]
okay!

**Comment by rakeshJn** [comment]
hi @deveshgoyal1000 there is an initial version of docker-compose, we have tried it with podman-compose though. It brings up catalog, minio based object store a data loader and the lakevision image itself. Hope it helps.

**Comment by rakeshJn** [comment]
This is no longer valid as we have moved to use daft for showing sample data and there, the limit is working good.... closing it.

**Comment by deveshgoyal1000** [comment]
okay sir!
